/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author BangKho
 */
public class Latihan1 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan1
     */
    public Latihan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_judul = new javax.swing.JLabel();
        label_nama = new javax.swing.JLabel();
        label_kelas = new javax.swing.JLabel();
        label_alamat = new javax.swing.JLabel();
        label_alamat1 = new javax.swing.JLabel();
        label_kelas1 = new javax.swing.JLabel();
        label_nama1 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Kelas = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        Alamat1 = new javax.swing.JTextField();
        Kelas1 = new javax.swing.JTextField();
        Nama1 = new javax.swing.JTextField();
        OKE = new javax.swing.JButton();
        author = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        label_judul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_judul.setText("Formulir Siswa");
        getContentPane().add(label_judul);
        label_judul.setBounds(120, 20, 180, 50);

        label_nama.setText("Nama");
        getContentPane().add(label_nama);
        label_nama.setBounds(40, 80, 60, 20);

        label_kelas.setText("Kelas");
        getContentPane().add(label_kelas);
        label_kelas.setBounds(40, 120, 60, 30);

        label_alamat.setText("Alamat");
        getContentPane().add(label_alamat);
        label_alamat.setBounds(40, 160, 60, 30);

        label_alamat1.setText("Alamat");
        getContentPane().add(label_alamat1);
        label_alamat1.setBounds(40, 340, 60, 14);

        label_kelas1.setText("Kelas");
        getContentPane().add(label_kelas1);
        label_kelas1.setBounds(40, 300, 60, 14);

        label_nama1.setText("Nama");
        getContentPane().add(label_nama1);
        label_nama1.setBounds(40, 260, 60, 14);

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Nama);
        Nama.setBounds(110, 80, 240, 30);
        getContentPane().add(Kelas);
        Kelas.setBounds(110, 120, 240, 30);
        getContentPane().add(Alamat);
        Alamat.setBounds(110, 160, 240, 30);
        getContentPane().add(Alamat1);
        Alamat1.setBounds(110, 340, 240, 30);
        getContentPane().add(Kelas1);
        Kelas1.setBounds(110, 300, 240, 30);

        Nama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama1ActionPerformed(evt);
            }
        });
        getContentPane().add(Nama1);
        Nama1.setBounds(110, 260, 240, 30);

        OKE.setText("Proses");
        OKE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKEActionPerformed(evt);
            }
        });
        getContentPane().add(OKE);
        OKE.setBounds(170, 210, 90, 30);

        author.setText("Ahmad Khoirudin / 03 / XIRPL5");
        getContentPane().add(author);
        author.setBounds(20, 400, 200, 14);

        setBounds(0, 0, 416, 496);
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void Nama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nama1ActionPerformed

    private void OKEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKEActionPerformed
        String nama = Nama.getText();
        Nama1.setText(nama);
        String kelas = Kelas.getText();
        Kelas1.setText(kelas);
        String alamat = Alamat.getText();
        Alamat1.setText(alamat);
    }//GEN-LAST:event_OKEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField Alamat1;
    private javax.swing.JTextField Kelas;
    private javax.swing.JTextField Kelas1;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Nama1;
    private javax.swing.JButton OKE;
    private javax.swing.JLabel author;
    private javax.swing.JLabel label_alamat;
    private javax.swing.JLabel label_alamat1;
    private javax.swing.JLabel label_judul;
    private javax.swing.JLabel label_kelas;
    private javax.swing.JLabel label_kelas1;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_nama1;
    // End of variables declaration//GEN-END:variables
}
